catalog: ecommerce_dev

# Tables
bronze_schema: bronze
silver_schema: silver
gold_schema: gold


# Files
base_path: /mnt/ecommerce/

raw_path: /mnt/ecommerce/raw/
bronze_path: /mnt/ecommerce/bronze/
silver_path: /mnt/ecommerce/silver/
gold_path: /mnt/ecommerce/gold/